version: "3.8"
services:
  unitnspottedwebapi:
    image: unitnspottedwebapi
    container_name: unitnspottedwebapi_service
    depends_on: 
      - sqlserver
    command: ["./utility/wait-for-it.sh", "sqlserver_unitnspotted:1433", "--timeout=60"]
    environment: 
      - ASPNETCORE_APPLY_MIGRATIONS_AT_STARTUP=true
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=TestingPwd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/spotted_webapp_cert.pfx
    networks:
      - spottedunitnwebapp_network
    ports:
      - "8000:80"
      - "8001:443"
    volumes:
      - type: bind
        source: ./certificates
        target: /https
        read_only: true
        volume:
          nocopy: true
      - type: bind
        source: ./SpottedWebApi/configs/appsettings.json
        target: /app/appsettings.json
        read_only: true
        volume:
          nocopy: true
  sqlserver:
    image: unitnspottedsqlserver
    container_name: sqlserver_unitnspotted
    networks:
      - spottedunitnwebapp_network
    ports:
      - "1435:1433"
    volumes:
      - type: volume
        source: unitnspottedsqlserver_data
        target: /var/opt/mssql
    hostname: sqlserver_unitnspotted

networks: 
  spottedunitnwebapp_network:
    driver: bridge

volumes:
  unitnspottedsqlserver_data:
    external: true